# Generated by Django 3.0.7 on 2020-06-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200614_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Organization',
            new_name='Organizations',
        ),
    ]
