# Generated by Django 3.0.7 on 2020-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200620_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
